pin:
    path:   /usr/bin/pin
    bin: /usr/bin/pin/pin
    function-mode: name

pintool:
    arity:
        src: ./src/pintool/arity.cpp
        obj: ./bin/obj-intel64/arity.so
    type: 
        src: ./src/pintool/type.cpp
        obj: ./bin/obj-intel64/type.so
        prev_step: arity
    couple: 
        src: ./src/pintool/couple.cpp
        obj: ./bin/obj-intel64/couple.so
        prev_step: type
    memblock: 
        src: ./src/pintool/memblock.cpp
        obj: ./bin/obj-intel64/memblock.so
        prev_step: type

res:
    path: ./res

log:
    path: ./log

clang:
    lib-path: /usr/lib/x86_64-linux-gnu/libclang.so.1
    data-path: ./data/

test:
    proto:
        root: ./test/proto
        src: ./test/proto/src
        bin: ./test/proto/bin
        log: ./test/proto/log

